Improved notebook to html generation - use html_embed to in-line images into the html - add jupyter_contrib_nbextensions and remove pandoc from requirements.txt - use bash in Makefile - Only generate the Solution workbooks, since as static html, they are mostly   redundant.

diff --git a/docs/Makefile b/docs/Makefile
--- a/docs/Makefile
+++ b/docs/Makefile
@@ -1,6 +1,9 @@
 # Makefile for Sphinx documentation
 #
 
+# Make sure readthedocs uses bash
+SHELL := /bin/bash
+
 # You can set these variables from the command line.
 # DATE          = $(shell date +%Y-%m-%d_%H%M%S)
 SPHINXOPTS    = -w sphinx-errors.txt -T
@@ -108,19 +111,21 @@ tutorial_nb: ../examples/workshops/Module_*/*_Solution.ipynb
 		echo "** Execute and convert: $$nbfile"; \
 		name=$$(basename $$nbfile .ipynb); \
 		title=$$(echo $$name | sed "s/_/ /g"); \
-		cmd="jupyter nbconvert --to rst -y --output-dir=./tutorials $$nbfile"; \
-		if test -n "$$READTHEDOCS"; then \
+		cmd="jupyter nbconvert --to html_embed -y --output-dir=./tutorials $$nbfile"; \
+		if [[ -n "$${READTHEDOCS+x}" ]]; then \
 			echo "Generating static tutorials for ReadTheDocs..."; \
 			echo "  $$cmd"; \
 			$$cmd; \
 		else \
 			$$cmd --execute 2>/dev/null; \
+			if [[ "$$?" -ne 0 ]]; then \
+				echo "** Execute notebook failed: creating static"; \
+				$${cmd}; \
+			fi; \
 		fi; \
-		if [ $$? -ne 0 ]; then \
-			echo "** Execute notebook failed: creating static"; \
-			$${cmd}; \
-		fi; \
-	done
+		echo -e "$${title}:\n==================================================\n" > ./tutorials/$${name}.rst; \
+		echo -e ".. raw:: html\n    :file: $${name}.html\n" >> ./tutorials/$${name}.rst; \
+	done \
 
 tutorial_imgs: ../examples/workshops/Module_*/*.png
 	@echo "** Copy images from ../examples/workshops/* to $(BUILDDIR)/tutorials"
